client/src/App.js
client/src/components/invoices/addInvoice.js
client/src/components/invoices/index.js
client/src/sass/components/_invoices.scss
client/src/sass/main.css

Add invoice is still buggy.
- [] Complete, tested, ready to review and merge
- [] Test A Tested the routes with postman
- [] I have commented my code, particularly in hard-to-understand areas
- [] My changes generate no new warnings

Add Invoice functionality

---

server/README.md
server/controllers/changePassword.js
server/controllers/loginUser.js
server/models/invoices.js
server/models/users.js
server/routes/index.js

added get rout to login so JWT can be authorized if saved on clients machine.
- [ x] My code has been reviewed by at least one peer
- [ x] I have made corresponding changes to the documentation
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
- [ x] There are no merge conflicts

changePassword route working.  api/login get working

---

client/.eslintrc.json
client/package-lock.json
client/package.json
client/src/App.js
client/src/HOC/requireAuth.js
client/src/actions/index.js
client/src/components/Auth/signin.js
client/src/components/Auth/signup.js
client/src/components/invoices/addInvoice.js
client/src/components/landing/index.js
client/src/components/sidebar/index.js
client/src/reducers/index.js
client/src/reducers/indexss.js
client/yarn.lock

Max pay me

---

server/README.md
server/config/dev.js
server/config/prod.js
server/controllers/invoice/newInvoice.js
server/controllers/user/changePassword.js
server/controllers/user/loginUser.js
server/controllers/user/registerUser.js
server/models/invoices.js
server/routes/index.js

updated documentation, newInvoice endpoint. changed dev key to start local mongoDB.

Ajs branch

---

.gitignore
package-lock.json
package.json
server/app.js
server/routes/index.js

file structure change to push to heroku.

changed file structure to host on heroku

---

client/src/actions/index.js
client/src/components/invoices/deleteInvoice.js
client/src/components/invoices/index.js
client/src/components/invoices/viewInvoice.js
client/src/sass/abstracts/_variables.scss
client/src/sass/components/_invoices.scss
client/src/sass/components/_sidebar.scss
client/src/sass/main.css

Still need add update functionality

Finished navigation design for /viewNote

---

server/controllers/user/loginUser.js

1 line change as requested by Max.  login user now populated invoices.

populate invoices during a user login

---

server/app.js
server/controllers/sendText.js
server/models/Reminder.js
server/routes/index.js
server/scheduler.js

- [] Complete, tested, ready to review and merge

changes for scheduling

---

client/src/HOC/requireAuth.js
client/src/components/billing/AdminBilling.js
client/src/components/payInvoice/ClientBilling.js

AdminBilling built.  Just needs styling

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/actions/invoices.js
client/src/components/billing/AdminBilling.js
client/src/components/billing/CheckoutForm.js
client/src/components/invoices/home/dataInvoice.js
client/src/components/invoices/home/index.js
client/src/components/invoices/home/pdf.js
client/src/components/settings/index.js
client/src/sass/components/_billing.scss
client/src/sass/components/invoices/_datainvoice.scss
client/src/sass/components/invoices/_invoices.scss
client/src/sass/components/invoices/_pdf.scss
client/src/sass/main.css
server/controllers/user/loginUser.js
server/routes/index.js

Max pay me- Pdf view is fully functional

---

client/src/components/invoices/home/dataInvoice.js

removed weekly <p> tag from dataInvoice.js added reminder shows

---

client/src/components/billing/AdminBilling.js
client/src/components/billing/ConnectStripe.js
client/src/components/payInvoice/ClientBilling.js

adjust stripe buttons and conenct stripe button to match add invoice

adjust stripe buttons and conenct stripe button to match add invoice

---

server/controllers/sendText.js
server/models/Reminder.js

Refactoring:
Everything inside of sendEmail.js was copied (Not removed) to Reminder.js so it can be used the same way as twilio api. Adjusted the Reminder schema to take in fields for the email reminder.
Tested and getting a success console.log but not getting email yet

Luis branch

---

client/package-lock.json
client/package.json
client/src/components/billing/AdminBilling.js
client/src/components/payInvoice/ClientBilling.js
client/src/components/reminders/reminders.js
client/src/sass/components/_billing.scss
client/src/sass/components/_reminder.scss
client/src/sass/components/reminders/_form.scss
client/src/sass/main.css

reminder styling complete

---

client/src/components/invoices/home/index.js
package-lock.json
server/controllers/invoice/addInvoice.js

completed issue#74 and 75

---

server/controllers/invoice/deleteInvoice.js

When deleting an invoice, the server will now delete all reminders that were associated with that invoice.  It will also now delete the invoice by the _id and not the invoice number.

refactored delete invoice to delete reminders

---

client/src/components/reminders/reminderForm.js
client/src/components/reminders/reminders.js
server/controllers/sendText.js
server/models/Reminder.js

change default remind to weekly

---

server/controllers/user/codeLogin.js
server/models/users.js
server/routes/index.js

starting recover password on server.  wanted to get userModel update merged ASAP.

added recovery to userModel

---

server/controllers/email/body.hbs

alight styling adjust of email

---

client/src/App.js
client/src/actions/auth.js
client/src/components/Auth/codeVerification.js
client/src/components/Auth/signin.js
client/src/components/settings/index.js
client/src/sass/components/_settings.scss
client/src/sass/components/auth/_signin.scss
client/src/sass/main.css
server/controllers/user/changePassword.js
server/controllers/user/codeLogin.js

Admin/freelancers now have the ability to login via a text message code sent to them.  will send to the phone number on file, if its not a cell number, they wont get the message...

Recover password
